import { ReactNode, Suspense } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Layout({ children }: { children?: ReactNode }) {
  return (
    <>
      <Head>
        <title>toryBids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/">
          <h1 className="text-8xl font-extrabold p-4 cursor-pointer mx-auto text-center">
            toryBids
          </h1>
        </Link>
      </header>
      <main className="p-4 container mx-auto min-h-screen">{children}</main>
      <footer className="sticky bottom-0 flex bg-white p-6 align-middle justify-center">
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="p-4 align-middle"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}

        <a href="https://order-order.com" className="p-4 align-middle">
          leadership data from Guido Fawkes
        </a>
        <a href="https://www.parliament.uk/" className="p-4 align-middle">
          member data from parliament.uk
        </a>

        <a
          href="https://github.com/alorslouis/tory-bid"
          className="p-4 align-middle"
        >
          GitHub
        </a>
      </footer>
    </>
  );
}
